name: Masks
main: cosmicnebula200\Masks\Masks
version: 1.0.0
api: 3.0.0
depend:
  - EconomyAPI

commands:
  mask:
    usage: /mask <type> <player>
    description: gives masks to a player
    permission: mask.command
permissions:
  mask.command:
    default: op
    description: permission to give masks to others
